name: test and deployment workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm run lint

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: 'leandromsilva.com.br'
    needs: build
    steps:
      - run: echo deploy-dev
