name: run-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: echo "Issa $env.JWT_SECRET"
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm test
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}